"""new fields in user model

Revision ID: 524172a5e77b
Revises: ae7a48f660b9
Create Date: 2020-06-14 10:38:55.457313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '524172a5e77b'
down_revision = 'ae7a48f660b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
