"""followers

Revision ID: 77423f002dff
Revises: 524172a5e77b
Create Date: 2020-06-14 12:47:32.492190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77423f002dff'
down_revision = '524172a5e77b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
